### ISSUE TITLE
Core functionality

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/Petit-Peripheral#1]
Because milestones aren't enough.
## Arguments
- [x] Basic conversion and validation
- [x] Optional arguments (60caf692404f22bf211b8b9fbf8aafeaee8aa33a)
- [x] Variable (i.e. `String...`) arguments (adc31670b8011ff850faa0f63c50c20c2c4bb424)
- [x] Per-argument error messages (rather than `Expected string, string` you have `Expected string, got number for argument #3`) (Infrastructure implemented in 2368626b8695441671064dd75944071c34ff4820, needs actual implementations - probably implement with #2) (Implemented a class for it in e9593faea44198bb886053b76a2d6450ae0c3cbc, but need a way to instantiate it).
- [x] Runtime conversion - finds classes at compile time, but they aren't compiled. (470b1255b69cc38feafeb3e461dda2879a6f6ada)
## Infrastructure
- [x] Transformers for custom annotations
- [x] Extending both petit and vanilla peripherals (Done in #7)
- ~~Preconditions - run before a method is called to ensure that it can be used.~~ - Not that fussed
- [ ] Documentation - ability to add a 'getDocumentation' (or whatever) function (see #6).
